[envs.default]
python = '3.8'
dependencies = [
    "pip>=22.0.0",
    # Make sure to update this when updating the build-requires in pyproject.toml
    "meson-python @ git+https://github.com/mesonbuild/meson-python.git@61bb2b3315f4e312558778022ca6e87ffaed2700"
]
skip-install = true

[envs.default.scripts]
clean_mesonpy = "python -c \"import shutil; shutil.rmtree('.mesonpy', ignore_errors=True)\""
install_editable = "python -m pip install --verbose  -e . --config-settings editable-verbose=true"
install = "python -m pip install --verbose ."

[envs.dist]
extra-dependencies = [
    "build",
    "pytest",
    "flake8",
    "typing_extensions",
]

[envs.dist.scripts]
build = [
    "python -m build --no-isolation --wheel --sdist --outdir ./dist",
]
install_whl = "python -m pip install --force-reinstall --find-links ./dist --no-index extype"
run_flake8 = "flake8 ./src/ ./tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics"
run_pytest = "pytest"
test = [
    "build",
    "install_whl",
    "run_flake8",
    "run_pytest"
]

[[envs.dist.matrix]]
python = ["37", "38", "39", "310", "311"]
