[build-system]
requires = ["scikit-build-core[rich,pyproject]"]
build-backend = "scikit_build_core.build"

[project]
name = "extypes"
version = "0.1.0"
authors = [{ name = "Xpo Development", email = "biny.xpo.dev" }]
description = "BuiltinsPlus is a module that allows you to extend builtins types."
requires-python = ">=3.7"

[tool.scikit-build]
wheel.packages = ["src/extypes"]
